### ISSUE TITLE
"#" comments are not supported

### ISSUE THREAD

**Issue by moruzerinho6** [Sdju/js-ini#18]
Given the following ini string to parse:

```INI
[Common]
WindowTitle=Project OutFox 5.3 Alpha
StepMania=Project OutFox
# Dedicated Character Display strings
ModelLoadError=Model for %s (%s) Has a invalid model. Please check if the model.txt file is correctly named and formatted.
ModelAnimLoadError=An animation file for %s's model (%s) is invalid or non-existant. Please check the animation folders and see if there's any file missing.
LocationLoadError=Current Location (%s) is missing its location model. Please check if the model.txt file is correctly named and formatted.
SongLoaderSingleSong=Random Song Play: Current Folder only contains 1 song. The game might get confused when picking the song via random. Selecting to index 1.
SongLoaderNoSongs=Random Song Play: No songs were found in your installation directory! Switching back to fallback music.
```

Calling `parse` will bring the following error: 

```
const error = new errors_1.ParsingError(line, lineNumber);
                      ^

ParsingError: Unsupported type of line: [4]"# Dedicated Character Display strings"
    at Object.parse (C:\Users\zerinho6\Desktop\fini\node_modules\js-ini\lib\parse.js:64:23)
    at load (C:\Users\zerinho6\Desktop\fini\load.js:26:26) {
  line: '# Dedicated Character Display strings',
  lineNumber: 4
}
```

Is there a reason # comments are not supported? VSCode and Github both supports # comments

**Comment by Sdju** [comment]
Hello!
You can pass the "comment" option (by default it's `;`)

**Comment by moruzerinho6** [comment]
> Hello! You can pass the "comment" option with `'#'` value (by default it's `;`)

Thanks for the reply, while I understand that I can pass a comment param, both "#" and ";" and comment keywords which are supported by standard, maybe a system to adopt both could be implemented?
